=== fuermiguel/ProyectoFinal/xml-resources/jaxb/cartelBinding/cartel.xsd
<?xml version="1.0" encoding="windows-1252"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/cartel"
    xmlns:tns="http://xml.netbeans.org/schema/cartel"
    elementFormDefault="qualified">
    <xsd:complexType name="tipoPie">
        <xsd:sequence>
            <xsd:element name="sponsor" maxOccurs="unbounded" type="xsd:string"/>
            <xsd:element name="fondo" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tipoCabecera">
        <xsd:sequence>
            <xsd:element name="imagen" type="xsd:string"/>
            <xsd:element name="fondo" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tipoPrincipal">
        <xsd:sequence>
            <xsd:element name="imagen" type="xsd:string"/>
            <xsd:element name="fondo" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tipoPlantilla">
        <xsd:sequence>
            <xsd:element name="cabecera" type="tns:tipoCabecera"/>
            <xsd:element name="principal" type="tns:tipoPrincipal"/>
            <xsd:element name="pie" type="tns:tipoPie"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="plantilla" type="tns:tipoPlantilla"/>
</xsd:schema>

=== fuermiguel/ProyectoFinal/Plantillas/plantilla.xml
<?xml version="1.0" encoding="windows-1252"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:plantilla
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://xml.netbeans.org/schema/cartel'
    xsi:schemaLocation='http://xml.netbeans.org/schema/cartel cartel.xsd'>
    <ns1:cabecera>
        <ns1:imagen></ns1:imagen>
        <ns1:fondo></ns1:fondo>
    </ns1:cabecera>
    <ns1:principal>
        <ns1:imagen></ns1:imagen>
        <ns1:fondo></ns1:fondo>
    </ns1:principal>
    <ns1:pie>
        <ns1:sponsor></ns1:sponsor>
        <ns1:sponsor></ns1:sponsor>
        <ns1:sponsor></ns1:sponsor>
        <ns1:sponsor></ns1:sponsor>
        <ns1:fondo></ns1:fondo>
    </ns1:pie>

</ns1:plantilla>

=== fuermiguel/ProyectoFinal/baseDeDatos/cartel1.xml
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<ns1:plantilla xmlns:ns1="http://xml.netbeans.org/schema/cartel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xml.netbeans.org/schema/cartel cartel.xsd">
  <ns1:cabecera>
    <ns1:imagen>cabecera1.png</ns1:imagen>
    <ns1:fondo>java.awt.Color[r=0,g=255,b=0]</ns1:fondo>
  </ns1:cabecera>
  <ns1:principal>
    <ns1:imagen>principal1.png</ns1:imagen>
    <ns1:fondo>java.awt.Color[r=0,g=255,b=0]</ns1:fondo>
  </ns1:principal>
  <ns1:pie>
    <ns1:sponsor>rebook.png</ns1:sponsor>
    <ns1:sponsor>adidas.png</ns1:sponsor>
    <ns1:sponsor>cocacola.png</ns1:sponsor>
    <ns1:sponsor>redbull.png</ns1:sponsor>
    <ns1:fondo>java.awt.Color[r=0,g=255,b=0]</ns1:fondo>
  </ns1:pie>
</ns1:plantilla>
